version: '3.9'

services:
  api-gateway:
    image: apigateaway
    build:
      context: .
      dockerfile: APIGateaway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - user-service
      - order-service
      - product-service

  user-service:
    image: userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "5001:8080"

  order-service:
    image: orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
      - "5002:8080"

  product-service:
    image: productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    ports:
      - "5003:8080"

  redis:
    image: redis:7
    ports:
      - "6379:6379"